config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  get    "login"     => "sessions#new"
  post   "login"     => "sessions#create"
  delete "logout"    => "sessions#destroy"
  get    "signup"    => "users#new"
  get    "about"     => "static_pages#about"
  get    "contact"   => "static_pages#contact"
  get    "help"      => "static_pages#help"
  get    "home"      => "static_pages#home"
  root   "static_pages#home"
  resources :entries
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :entries, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :entries do
    resources :comments
  end

end

app/views/shared/_comment_form.html.erb
<%= form_for [entry, entry.comments.build] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Give your comment" %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <%= f.submit (t"_entry_form_btn"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_entry_form.html.erb
<%= form_for(entry) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: (t"_entry_form_TA") %>
  </div>
  <%= f.submit (t"_entry_form_btn"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="entries">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to (t"_user_info_btn"), current_user %></span>
<span><%= pluralize(current_user.entries.count, "entry") %></span>